
mex -v '-IC:\Program Files\Eigen3\include\eigen3' ...
    '-IC:\Program Files\SuiteSparse\include' ...
'-LC:\Program Files\SuiteSparse\lib' ...
'-LC:\Program Files\SuiteSparse\lib64\lapack_blas_windows' ...
     SIMengine/Classes/stdafx.cpp SIMengine/Classes/mersenne.cpp ...
     SIMengine/Classes/SIMcore.cpp SIMengine/Classes/SIMparameters.cpp ...
     SIMengine/Classes/ChemotaxisMapSuiteS.cpp SIMengine/Classes/NecrosisMapSuiteS.cpp...
     SIMengine/Classes/Environment.cpp SIMengine/Classes/TumorCells.cpp ...
     SIMengine/Classes/Lymphocytes.cpp SIMengine/Classes/Macrophages.cpp ...
     SIMengine_interface_mex.cpp ...
 -lamd -lcamd -lccolamd -lcholmod -lcolamd -lmetis -lsuitesparseconfig -lcxsparse -lblas -llapack

 copyfile('stdafx.mexw64','SIMengine_interface_mex.mexw64')